short_url/urls.py
from django.conf.urls import url

from . import views

app_name = 'short_url'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^list$', views.list, name='list'),
    url(r'^(?P<short_url_id>[0-9]+)/$', views.open_url, name='open_url'),
    url(r'^detail/(?P<short_url_id>[0-9]+)/$', views.detail, name='url_detail'),
    url(r'^add_url$', views.add_url, name='add_url'),
]

urlshooter/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('short_url.urls')),
]

short_url/models.py
from django.db import models
from django.utils import timezone


class ShortUrl(models.Model):
    url = models.URLField('site url', db_index=True, unique=True)
    visits = models.IntegerField('visit counter', default=0)
    created_at = models.DateTimeField('created datetime', editable=False)

    def save(self, *args, **kwargs):
        if self.created_at is None:
            self.created_at = timezone.now()

        return super(ShortUrl, self).save(*args, **kwargs)

    def __str__(self):
        return self.url

    def get_absolute_url(self):
        from django.core.urlresolvers import reverse
        return reverse('short_url:url_detail', args=[self.id])

    @classmethod
    def ordered_urls(cls):
        return cls.objects.order_by('-visits', '-created_at')

short_url/forms.py
from django import forms

from .models import ShortUrl


class CreateShortUrlForm(forms.Form):
    url = forms.CharField(max_length=255, required=True)

short_url/views.py
from django.shortcuts import render, redirect,  get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .models import ShortUrl
from .forms import CreateShortUrlForm


def index(request):
    popular_urls = ShortUrl.ordered_urls()[:20]
    return render(request, 'short_url/index.html', {'popular_urls': popular_urls})


def open_url(request, short_url_id):
    short_url = get_object_or_404(ShortUrl, pk=short_url_id)
    short_url.visits += 1
    short_url.save()
    return redirect(short_url.url)


def detail(request, short_url_id):
    short_url = get_object_or_404(ShortUrl, pk=short_url_id)
    full_url = request.build_absolute_uri(short_url.get_absolute_url())
    return render(request, 'short_url/detail.html', {'short_url': short_url, 'url': full_url})


def add_url(request):
    form = CreateShortUrlForm(request.POST)
    if not (request.method == 'POST' and form.is_valid()):
        return redirect(request.path_info)

    short_url, created = ShortUrl.objects.get_or_create(url=request.POST['url'])
    return render(request, 'short_url/detail.html', {'short_url': short_url})


def list(request):
    urls_list = ShortUrl.ordered_urls()
    page = request.GET.get('page', 1)

    paginator = Paginator(urls_list, 10)

    try:
        urls_list = paginator.page(page)
    except PageNotAnInteger:
        urls_list = paginator.page(1)
    except EmptyPage:
        urls_list = paginator.page(paginator.num_pages)

    return render(request, 'short_url/list.html', {'urls_list': urls_list})

short_url/templates/urls_table.html
{% load urls_table %}
<table>
    <tr>
      <td> Короткий url </td>
      <td> Кол-во посещений </td>
      <td> Куда ведет </td>
      <td> Дата создания </td>
    </tr>
    {% for short_url in urls_list %}
        <tr>
          <td> <a href="{% url 'short_url:url_detail' short_url.id %}">{{ short_url.id }}</a></td>
          <td> {{ short_url.visits }} </td>
          <td> <a href="{{ short_url.url }}">{{ short_url.url }}</a></td>
          <td> {{ short_url.created_at }} </td>
        </tr>
    {% endfor %}
</table>

templates/short_url/detail.html
<h1>Информация о короткой ссылке</h1>
<ul>
    <li>id: {{ short_url.id }}</li>
    <li>Короткая ссылка:<a href="{{ short_url.get_absolute_url }}">{{ url }}</a></li>
    <li>Ссылка ведет на url: <a href="{{ short_url.url }}">{{ short_url.url }}</a></li>
    <li>Переходов {{ short_url.visits }}</li>
    <li>Дата создания {{ short_url.created_at }}</li>
</ul>

templates/short_url/index.html
{% load urls_table %}

<h1>URL SHOOTER</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'short_url:add_url' %}" method="post">
{% csrf_token %}
    <input id="short_url_url" type="text" name="url" />
    <label for="short_url_url">Ссылка</label><br />
<input type="submit" value="Получить короткий url" />
</form>

{% urls_table_show popular_urls %}

templates/short_url/list.html
{% load urls_table %}

<h1>Список ссылок</h1>

{% urls_table_show urls_list %}

<div class="pagination">
    <span class="step-links">
        {% if urls_list.has_previous %}
            <a href="?page={{ urls_list.previous_page_number }}">предыдущая</a>
        {% endif %}

        <span class="current">
            Страница {{ urls_list.number }} из {{ urls_list.paginator.num_pages }}.
        </span>

        {% if urls_list.has_next %}
            <a href="?page={{ urls_list.next_page_number }}">следующая</a>
        {% endif %}
    </span>
</div>